---
name: unit_specs

"on":
  pull_request:
  push:
    branches:
      - main

jobs:
  unit:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        clean: true
    - run: which ruby
    - run: ruby -v
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.1"
        bundler-cache: false
    - run: which ruby
    - run: ruby -v
    - run: bundle update --bundler
    - run: bundle install
    - run: bundle exec rake spec:unit
    - run: bundle exec rake component_specs
